### ISSUE TITLE
signed version on NuGet?

### ISSUE THREAD

**Issue by bdemarzo** [mj1856/SimpleImpersonation#1]
Great little library. Any chance of creating a signed version of it on NuGet?

**Comment by mj1856** [comment]
FYI, https://github.com/dsplaisted/strongnamer is a better option these days.

**Comment by mj1856** [comment]
For more current guidance, see FAQ Item 1 here:

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md


Also note from https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

> Do not rely on strong names for security. They provide a unique identity only.
