### ISSUE TITLE
Could not impersonate the elevated user.  LogonUser returned error code 1326.

### ISSUE THREAD

**Issue by ovidiaconescu** [mj1856/SimpleImpersonation#12]
I'm getting this error when I try to impersonate an account for File.Copy(..)

**Comment by mrichman** [comment]
Have you read this? [http://stackoverflow.com/questions/17332977/logonuser-failed-with-error-code-1326](http://stackoverflow.com/questions/17332977/logonuser-failed-with-error-code-1326)

**Comment by mj1856** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms681385.aspx

> `ERROR_LOGON_FAILURE`
> 1326 (0x52E)
> The user name or password is incorrect.

There are a variety of reasons this could be occurring.  Unfortunately, I can't really help with that.  This library just wraps the `LogonUser` APIs in Windows - so if you are passing the correct credentials and it doesn't work, then look into reasons why `LogonUser` might fail on other sites.

Thanks.
