### ISSUE TITLE
Impersonation and Activator.CreateInstance() on remote machine

### ISSUE THREAD

**Issue by mrichman** [mj1856/SimpleImpersonation#13]
Is there any way to wrap a call to `Activator.CreateInstance()` against a remote machine with alternate credentials? No matter which value for `LogonType` I pass, I get Access Denied.

```
using (Impersonation.LogonUser(domain, username, password, LogonType.Interactive))
{
    try
    {
        Type t = Type.GetTypeFromProgID("Microsoft.Update.Session", hostname, true);
        var comobj = Activator.CreateInstance(t); // <== throws UnauthorizedAccessException
        UpdateSession session = (UpdateSession) comobj;
        IUpdateSearcher updateSearcher = session.CreateUpdateSearcher();

        var count = updateSearcher.GetTotalHistoryCount();
				
				...
				
				
```
This works fine from Powershell if I start the prompt as a different user, by the way:

```
PS C:\WINDOWS\system32> $updatesession = [activator]::CreateInstance([type]::GetTypeFromProgID("Microsoft.Update.Session", $hostname))
```

**Comment by mj1856** [comment]
Sorry, I don't know much about this.  I found [this question on StackOverflow](http://stackoverflow.com/q/13278831/634824) which it looks like you've already seen (from comments).  Looking at that code, it would seem that auth info has to be passed separately.
