### ISSUE TITLE
Published 1.1.0 Nuget package adds no files to Project

### ISSUE THREAD

**Issue by jbattermann** [mj1856/SimpleImpersonation#16]
The NuGet package as it is published on NuGet.org ([1.1.0 as of writing](https://www.nuget.org/packages/SimpleImpersonation/1.1.0)) contains a .nuspec with no file references - neither for net20 nor net40.. so whenever adding the package to a project, nothing really happens.

The [.nuspec in the repository](https://github.com/mj1856/SimpleImpersonation/blob/master/SimpleImpersonation/SimpleImpersonation.nuspec) itself appears to only have a net20 section and I am not entirely sure how you build/package & publish the package (manually or i.e. via a ci / build system) but while developers can manually add a reference to the assembly, it is a bit confusing.. :)

**Comment by mj1856** [comment]
It seems to work just fine for me.  The package contains the dll, pdb, and xml, and the reference is added automatically when I add the package to a project.

I build by manually executing the simple [build.cmd](https://github.com/mj1856/SimpleImpersonation/blob/master/build.cmd) in the repo, then manually push to nuget with `nuget push ...` after that.

Nuget picks up most of the files itself, based on the project reference.  I add the `net20` section manually in the nuspec to handle the dual targeting.

**Comment by jbattermann** [comment]
Matt - I just tried again and .. mmm. no I can't confirm it worked. Steps I performed:

- Open Visual Studio (in my case VS2013 Update 5)
- Create a new .Net 4.5 Console Aplication
- Try to add `SimpleImpersonation` NuGet Package (2.0.1)

and this error occurs:

![2016-06-16 11_13_37-summary](https://cloud.githubusercontent.com/assets/828/16111713/18a5bf58-33b4-11e6-95e5-e995180d3bfc.png)

And the Package Manager Output shows / says:

```
------- Installing...SimpleImpersonation 2.0.1 -------
Installing 'SimpleImpersonation 2.0.1'.
Added file 'SimpleImpersonation.dll' to folder 'SimpleImpersonation.2.0.1\lib\net20'.
Added file 'SimpleImpersonation.pdb' to folder 'SimpleImpersonation.2.0.1\lib\net20'.
Added file 'SimpleImpersonation.xml' to folder 'SimpleImpersonation.2.0.1\lib\net20'.
Added file 'SimpleImpersonation.dll' to folder 'SimpleImpersonation.2.0.1\lib\net40-Client'.
Added file 'SimpleImpersonation.xml' to folder 'SimpleImpersonation.2.0.1\lib\net40-Client'.
Added file 'SimpleImpersonation.2.0.1.nupkg' to folder 'SimpleImpersonation.2.0.1'.
Successfully installed 'SimpleImpersonation 2.0.1'.
Adding 'SimpleImpersonation 2.0.1' to ConsoleApplication2.
For adding package 'SimpleImpersonation 2.0.1' to project 'ConsoleApplication2' that targets 'net45',
>> Assembly references are being added from 'lib\net40-Client'
Added file 'packages.config'.
Added file 'packages.config' to project 'ConsoleApplication2'
Install failed. Rolling back...
Operation failed.
==============================
```

The packages.config in the project does contain SimpleImpersonation:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="SimpleImpersonation" version="2.0.1" targetFramework="net45" />
</packages>
```

but no Assembly reference was added to the project.

**Comment by mj1856** [comment]
That's odd...  I did the same thing on VS2015 and it works.  I'll test under VS2013 and see what happens.

Can you tell me which version of Nuget you have?  Does it work if you update nuget via VS tools and extensions?

**Comment by jbattermann** [comment]
Yeah I can confirm it works here (different office / machine) on VS2015 with NuGet 3.4(.4).. weird - I'll check tomorrow on the VS2013.5 machine and let you know.

**Comment by jbattermann** [comment]
It also works in VS2013 Update 5 w/ NuGet 2.8.6 (latest version for VS2013). So whatever is causing it on the other machine, it is localized to that one and I'll go ahead and close the issue.

Cheers!
-J
