### ISSUE TITLE
Returning wrong error code

### ISSUE THREAD

**Issue by mj1856** [mj1856/SimpleImpersonation#17]
Need to return the Win32 `NativeErrorCode` in the `ImpersonationException` instead of the `ErrorCode` - which is just an HResult handle.

For example, login failure should be code `1326`, not `-2146232832` (`0x80131600`)

**Comment by mj1856** [comment]
@jbattermann - Do you agree?

**Comment by mj1856** [comment]
Should it be in a separate `NativeErrorCode` property like `Win32Exception` has it? Or just return it in the `ErrorCode` property?

**Comment by jbattermann** [comment]
Yeah - sorry I overlooked that - primarily I think the .`NativeErrorCode` is the one of interest here but I'd keep the two separate and actually expose them both in your custom exception.

**Comment by mj1856** [comment]
Yeah, I was thinking the same thing.  Otherwise it's a breaking change again, for no good reason. :wink:

**Comment by mj1856** [comment]
Done in 2.0.1.  Thanks.

**Comment by jbattermann** [comment]
:+1:
