### ISSUE TITLE
Assembly has not strong-named

### ISSUE THREAD

**Issue by gdbd** [mj1856/SimpleImpersonation#23]
Caused error:
System.IO.FileLoadException: Could not load file or assembly 'SimpleImpersonation, Version=2.0.1.27158, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Because of this it not possible to use with signed assemblies

**Comment by mj1856** [comment]
Dup #1
