### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by felickz** [mj1856/SimpleImpersonation#26]
Is DNC support possible on Windows OS?

**Comment by mj1856** [comment]
I suppose this is possible now, at least [in theory](https://docs.microsoft.com/en-us/dotnet/standard/native-interop).  I'll investigate.

Also, would be good to know if there is something roughly equivalent to do for other platforms?

**Comment by danielcrenna** [comment]
It's possible, but you have to change your API so that you can access `WindowsIdentity.RunImpersonated` using an `Action` or `Func<T>`, which basically means passing that closure into a static method rather than in a `using` scope.

**Comment by mj1856** [comment]
This is complete with version 3.0.0.  See the readme for the new and improved API.  Note this is a breaking change, which takes an action or function delegate.  The previous API is no longer supported.

It is still Windows-only.  I would gladly accept pull requests to add support for other platforms.
