### ISSUE TITLE
[Question] Why is run as administrator required?

### ISSUE THREAD

**Issue by codenesium** [mj1856/SimpleImpersonation#29]
I'm trying to update the user and password on a windows service from an application that is ran without administrator rights. On Windows 7 I can impersonate the domain admin and then call sc.exe with no problems. Under Windows 10 even though I'm impersonating a domain admin I can't make these changes unless I right click and run the app as administrator. UAC is turned off. Have you ran into anything like that with windows 10? Your library is great BTW. 

I have a SO question out there as well https://stackoverflow.com/questions/51862476/net-impersonation-not-working

**Comment by codenesium** [comment]
This was happening because of UAC. It was turned off but you need the registry setting and a reboot too.

https://stackoverflow.com/questions/51862476/net-impersonation-not-working

**Comment by mj1856** [comment]
I strongly recommend you turn UAC back on. It's a vital security feature of the operating system.

I answered your question with more detail, over on StackOverflow.

https://stackoverflow.com/a/52048084/634824
