### ISSUE TITLE
Make it a Middleware

### ISSUE THREAD

**Issue by brunotourinho** [mj1856/SimpleImpersonation#30]
I was looking for some projects to make it easy to access a shared network folder. Found yours and David Whitehead's.

He also implemented the impersonation as a middleware. 
 
https://github.com/lilpug/ASP.NET-Core-Impersonation

**Comment by mj1856** [comment]
Thanks, but I think David (@lilpug) has done a good job with his middleware.  I don't see the need to re-implement that here.   One certainly could use SimpleImpersonation to do the actual impersonation bits, if you or David wanted to take a dependency - but I don't think there's necessarily an advantage.  At the end of the day, we're all calling `LogonUser`.
