### ISSUE TITLE
Not working on Windows Server 2012 R2

### ISSUE THREAD

**Issue by NihadOb** [mj1856/SimpleImpersonation#45]
I am trying to access UNC but it is not working on Framework 4.7.2/Core 2.2 version. If I try old method with WindowsImpersonationContext it is working but Core is not supporting WindowsImpersonationContext.

**Comment by mj1856** [comment]
Please provide some code example.  Also, what do you mean precisely by not working?  At all, or intermittently? Are you using async code in your impersonation block?  Are both machines joined to the same domain?
