### ISSUE TITLE
Impresonation with current user

### ISSUE THREAD

**Issue by JulienLegrand** [mj1856/SimpleImpersonation#49]
Hi, thank you for your work.
I want to know if it is possible to impersonate with the current connected user in a MVC application?
I cannot create a new UserCredentials, i don't know the user password (and don't want to know it).
Is it possible to use CredentialCache.DefaultCredentials or CredentialCache.DefaultNetworkCredentials as a UserCredentials?

Thx, Julien Legrand

**Comment by alex-jitbit** [comment]
+1.

There's already a private method that allows this (passing token instead of credentials). Please make it public

**Comment by mj1856** [comment]
Sorry, but I don't understand the request. It sounds like you just want to use `WindowsIdentity.RunImpersonated` or `WindowsIdentity.Impersonate`.  You don't need this library to do that.  Is there something more you need?

**Comment by mj1856** [comment]
@JulienLegrand - I'm closing this.  If you need more than the built-in `WindowsIdentity.RunImpersonated` or `WindowsIdentity.Impersonate` functions, please elaborate and I will reopen if warranted.  Thanks.
